name: Circle
version: 1.6.4
date: 2021-02-22
description: |
    Adjoint groups of finite rings

authors:
    - name: Alexander Konovalov
      url: https://alexk.host.cs.st-andrews.ac.uk
    - name: Panagiotis Soules
      url: mailto:psoules@math.uoa.gr

maintainers:
    - name: Alexander Konovalov
      url: https://alexk.host.cs.st-andrews.ac.uk

GAP: ">=4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/circle
readme: README.md
packageinfo: https://gap-packages.github.io/circle/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/circle/releases/download/v1.6.4/circle-1.6.4.tar.gz

abstract: |
    The <span class="pkgname">Circle</span> package provides functionality for computations in adjoint groups of finite associative rings. It allows to construct circle objects that will respect the circle multiplication r*s=r+s+rs, create multiplicative groups, generated by such objects, and compute groups of elements, invertible with respect to this operation. Also it may serve as an example of extending the GAP system with new multiplicative objects.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
